

- name: install epel-release
  dnf:
    name: epel-release
    state: present

- name: dnf install
  dnf:
    name: "{{packages}}"
  vars:
    packages:
      - dkms
    enablerepo: epel-release


- name: import key　
  shell: rpm --import http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

- name: Remote RPM install with dnf(for nkf install)
  yum: name=http://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/n/nkf-2.1.3-5.el7.x86_64.rpm


- name: dnf install
  dnf:
    name: "{{packages}}"
  vars:
    packages:
      - ccid
      - pcsc-lite-devel
    enablerepo: epel-release

- name: download & unarchive pcsc-perl
  unarchive:
    src: http://search.cpan.org/CPAN/authors/id/W/WH/WHOM/pcsc-perl-1.4.13.tar.bz2
    dest: "{{ src_dir }}"
    copy: no

- name: perl Makefile.PL #makeファイルが作成されない場合のエラー処理入れたい　
  shell: cd /usr/local/src/pcsc-perl-1.4.13/ && perl Makefile.PL



- name: make all
  make:
    chdir: "{{ src_dir }}/pcsc-perl-1.4.13"
    target: all
      
- name: make install
  make:
    chdir: "{{ src_dir }}/pcsc-perl-1.4.13"
    target: install
  become: yes



- name: download & unarchive pcsc-tools
  unarchive:
    src: https://launchpad.net/ubuntu/+archive/primary/+files/pcsc-tools_1.4.23.orig.tar.gz
    dest: "{{ src_dir }}"
    copy: no


- name: make all
  make:
    chdir: "{{ src_dir }}/pcsc-tools-1.4.23"
    target: all
      
- name: make install
  make:
    chdir: "{{ src_dir }}/pcsc-tools-1.4.23"
    target: install
  become: yes




