#- name: bbbb
#  dnf:
#    name: docker-ce
#    state: latest
#    enablerepo: https://download.docker.com/linux/centos/docker-ce.repo



- name: dnf install git,samba
  dnf:
    name: "{{packages}}"
  vars:
    packages:
      - git
      - samba

- name: copy a directory
  copy:
    src: files/smb.conf
    dest: /etc/samba
    mode: 0577



- name: enable samba service
  systemd:
    name: smb
    state: restarted
    enabled: yes



#- name: upgrade all packages
#  dnf:
#    name: "*"
#    state: latest

- name: dnf list
  dnf:
    list: installed


- name: get server information
  command: "{{ item }}"
  with_items:
    - 'hostname'
    - 'cat /etc/redhat-release'
    - 'uname -a'
    - 'dnf list installed'


